default: # default is development connection
    type: "postgres"
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "postgres"
    database: "postgres"
    entities: ["./src/entities/*.\"ts,js\""]
    migrations: ["./src/database/migrations/*.\"ts,js\""]
    cli: { "migrationsDir": "./src/database/migrations" }

custom: # custom connection with sqlite if project allows it dont need timestamp data type and so on
    type: "sqlite"
    database: "sqlite/development.sql"
    entities: ["./src/entities/*.ts"]
    migrations: ["./src/database/migrations/*.ts"]
    cli: { "migrationsDir": "./src/database/migrations" }


